// Generated by LiveScript 1.2.0
var gulp, concat, uglify, rename, path, jasmine, combineFileName, libsBower, css;
gulp = require('gulp');
concat = require('gulp-concat');
uglify = require('gulp-uglify');
rename = require('gulp-rename');
path = require('path');
jasmine = require('gulp-jasmine');
combineFileName = function(src, names, extension){
  return names.map(function(v){
    return path.join(src, v) + extension;
  });
};
libsBower = combineFileName('bower_components', ['mithril/mithril', 'jquery/dist/jquery', 'lodash/dist/lodash', 'bilby.js/bilby', 'selectize/dist/js/standalone/selectize'], '.js');
css = combineFileName('css/', ['selectize', 'main'], '.css');
gulp.task('css', function(){
  var dest;
  dest = 'dist/static/css';
  return gulp.src(css).pipe(concat('all.css')).pipe(gulp.dest(dest));
});
gulp.task('libraries', function(){
  var dest, destLib;
  dest = 'dist/static/js';
  destLib = 'js/lib';
  return gulp.src(libsBower).pipe(gulp.dest(destLib)).pipe(concat('all-libraries.js')).pipe(gulp.dest(dest)).pipe(rename('all-libraries.min.js')).pipe(uglify()).pipe(gulp.dest(dest));
});
gulp.task('scripts', function(){
  var dest;
  dest = 'dist/static/js';
  return gulp.src('./js/*.js').pipe(concat('all.js')).pipe(gulp.dest(dest)).pipe(rename('all.min.js')).pipe(uglify()).pipe(gulp.dest(dest));
});
gulp.task('watch', function(){
  return gulp.watch(libsBower.concat(app, css), ['libraries', 'scripts', 'css']);
});
gulp.task('default', ['css', 'libraries', 'scripts', 'watch']);